FROM nginx:alpine
LABEL authors="anastasiaoreskina"

COPY about.html /usr/share/nginx/html
COPY contact.html /usr/share/nginx/html
COPY frog.html /usr/share/nginx/html
COPY index.html /usr/share/nginx/html

EXPOSE 80